# Generated by Django 2.2 on 2020-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='criteria_no_4',
        ),
        migrations.RemoveField(
            model_name='essaysubmission',
            name='ambiguity_score',
        ),
        migrations.AlterField(
            model_name='essay',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='Essay End Date and Time'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Essay Start Date and Time'),
        ),
    ]
