# Generated by Django 2.2 on 2020-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_school_year',
            field=models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022')], default='20', max_length=1, verbose_name='School Year'),
        ),
    ]
