# Generated by Django 2.2 on 2020-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_unit',
            field=models.IntegerField(default=3, verbose_name='Course Units'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_school_year',
            field=models.CharField(choices=[('1', '2019-2020'), ('2', '2020-2021'), ('3', '2021-2022')], default='20', max_length=1, verbose_name='School Year'),
        ),
    ]
