# Generated by Django 2.2 on 2020-02-13 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200213_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Essay Checked Date'),
        ),
    ]
