# Generated by Django 2.2 on 2020-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200219_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='score',
            name='essaySubmission',
        ),
        migrations.RemoveField(
            model_name='word',
            name='essay',
        ),
        migrations.AddField(
            model_name='essay',
            name='word',
            field=models.CharField(default='', max_length=10000, verbose_name='Words'),
        ),
        migrations.DeleteModel(
            name='Criterion',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
