# Generated by Django 2.2 on 2020-02-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200220_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='word',
            new_name='words',
        ),
    ]
